//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settings
    {
        public long Id { get; set; }
        public string SaveRootFolder { get; set; }
        public string SaveImagePath { get; set; }
        public string SaveTextPath { get; set; }
        public Nullable<long> StartOnWindows { get; set; }
    }
}
